---
- hosts: bigip_devices
  connection: local
  gather_facts: false
  tasks:
  - name: Add Webserver A
    bigip_node:
      provider: "{{ provider }}"
      name: "10.128.20.104"
      host: "10.128.20.104"

  - name: Add Webserver B
    bigip_node:
      provider: "{{ provider }}"
      name: "10.128.20.105"
      host: "10.128.20.105"

  - name: Create Webserver Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "ansible_webserver_pool"
      lb_method: "round-robin"
      monitors:
      - http
      - tcp
      monitor_type: and_list

  - name: Add Webserver A to Webserver Pool
    bigip_pool_member:
      provider: "{{ provider }}"
      pool: "ansible_webserver_pool"
      host: "10.128.20.104"
      port: 80

  - name: Add Webserver B to Webserver Pool
    bigip_pool_member:
      provider: "{{ provider }}"
      pool: "ansible_webserver_pool"
      host: "10.128.20.105"
      port: 80
