---
- hosts: bigip_devices
  connection: local
  tasks:
  - name: Remove Webserver Pool
    bigip_pool:
      server: {{ bigip_server }}
      user: {{ bigip_username }}
      password: {{ bigip_password }}
      name: "ansible_webserver_pool"
      lb_method: "round-robin"
      monitors:
      - http
      bigip_pool_member:
      - "10.128.20.104:80"
      - "10.128.20.105:80"
      validate_certs: False
      state: absent
