---
- hosts: bigip_devices
  connection: local
  tasks:
  - name: Create Webserver Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "ansible_webserver_pool"
      lb_method: "round-robin"
      monitors:
        - http
        - tcp
      monitor_type: and_list
      state: absent
